// Golden Shine — bilingual website copy (EN / ES). Exposed as window.GsCopy.
window.GsCopy = {
  en: {
    nav: { services: 'Services', how: 'How it works', reviews: 'Reviews', contact: 'Contact', book: 'Get a quote', call: 'Call us' },
    hero: {
      eyebrow: 'Home & Office Cleaning',
      titleA: 'A sparkling clean,',
      titleScript: 'every single time',
      sub: 'Golden Shine brings vetted, insured cleaners to your door. Book in two minutes — we bring the supplies, the care, and the shine.',
      ctaPrimary: 'Get a free quote',
      ctaSecondary: 'See our services',
      stat1: '4.9/5 average rating',
      stat2: '2,400+ homes cleaned',
      trust: 'Insured & background-checked · 100% satisfaction guarantee',
    },
    services: {
      eyebrow: 'What we do',
      title: 'Cleaning for every space',
      sub: 'From a quick refresh to a top-to-bottom deep clean — pick what fits.',
      items: [
        { icon: 'Home2', name: 'House Cleaning', desc: 'Regular upkeep of kitchens, baths, floors and living spaces.', from: 'from $89' },
        { icon: 'Building', name: 'Office & Commercial', desc: 'Reliable cleaning for offices, clinics and storefronts.', from: 'custom' },
        { icon: 'Sparkles', name: 'Deep Cleaning', desc: 'A detailed, top-to-bottom reset for the whole home.', from: 'from $189' },
        { icon: 'Truck', name: 'Move In / Move Out', desc: 'Leave it spotless — or arrive to a fresh, clean start.', from: 'from $229' },
        { icon: 'Sofa', name: 'Carpet & Upholstery', desc: 'Steam-cleaned carpets, rugs and furniture.', from: 'from $99' },
        { icon: 'Wand', name: 'Post-Construction', desc: 'Dust, debris and detail clean after a remodel.', from: 'custom' },
      ],
      cta: 'Get a quote',
    },
    how: {
      eyebrow: 'Simple & flexible',
      title: 'How it works',
      steps: [
        { icon: 'Calendar', name: 'Book online', desc: 'Tell us your space and pick a time that works for you.' },
        { icon: 'Spray', name: 'We clean', desc: 'Our insured team arrives on time with everything needed.' },
        { icon: 'CheckCircle', name: 'You relax', desc: 'Enjoy a spotless space — guaranteed, or we make it right.' },
      ],
    },
    why: {
      title: 'Why Golden Shine',
      items: [
        { icon: 'Shield', name: 'Insured & vetted', desc: 'Every cleaner is background-checked and fully insured.' },
        { icon: 'Leaf', name: 'Eco-friendly', desc: 'Safe, non-toxic products — kind to kids and pets.' },
        { icon: 'Clock', name: 'On time, always', desc: 'We respect your schedule and show up when we say.' },
        { icon: 'CheckCircle', name: '100% guarantee', desc: "Not happy? We'll re-clean it free within 24 hours." },
      ],
    },
    reviews: {
      eyebrow: 'Loved by locals',
      title: 'What our customers say',
      rating: '4.9 out of 5 · 312 reviews',
      items: [
        { name: 'Maria L.', city: 'Houston, TX', text: 'They left my kitchen absolutely spotless. Booking took two minutes and the team was so kind.', stars: 5 },
        { name: 'James P.', city: 'Houston, TX', text: 'We use Golden Shine for our office every week. Always on time, always thorough.', stars: 5 },
        { name: 'Aisha K.', city: 'Katy, TX', text: 'The deep clean before our move-out got us the full deposit back. Worth every penny.', stars: 5 },
      ],
    },
    quote: {
      eyebrow: 'Free, no obligation',
      title: 'Get your quote',
      sub: 'Tell us a bit about your space and we’ll text you a price within the hour.',
      name: 'Full name', namePh: 'Jane Doe',
      phone: 'Phone', phonePh: '(555) 123-4567',
      email: 'Email', emailPh: 'you@email.com',
      service: 'Service type', servicePh: 'Choose a service',
      serviceOpts: ['House Cleaning', 'Office & Commercial', 'Deep Cleaning', 'Move In / Move Out', 'Carpet & Upholstery', 'Post-Construction'],
      size: 'Property size', sizePh: 'Select size',
      sizeOpts: ['Studio / 1 bed', '2 bedrooms', '3 bedrooms', '4+ bedrooms', 'Office / commercial'],
      freq: 'How often?',
      freqOpts: ['One time', 'Weekly', 'Every 2 weeks', 'Monthly'],
      addons: 'Add-ons',
      addonOpts: ['Inside the oven', 'Interior windows', 'Inside the fridge', 'Laundry & folding'],
      submit: 'Request my quote',
      consent: 'I agree to be contacted about my quote.',
      successTitle: 'Quote requested!',
      successSub: "Thanks — we'll text you a price within the hour. Keep an eye on your phone.",
      again: 'Request another',
    },
    footer: {
      tagline: 'Home & office cleaning you can trust.',
      hours: 'Mon–Sat · 8am–7pm',
      area: 'Serving Houston & surrounding areas',
      col1: 'Services', col2: 'Company', col3: 'Get in touch',
      company: ['About us', 'Careers', 'Reviews', 'Gift cards'],
      rights: '© 2026 Golden Shine Cleaning Service. All rights reserved.',
    },
    langLabel: 'ES',
  },
  es: {
    nav: { services: 'Servicios', how: 'Cómo funciona', reviews: 'Reseñas', contact: 'Contacto', book: 'Cotizar', call: 'Llámanos' },
    hero: {
      eyebrow: 'Limpieza de Casas y Oficinas',
      titleA: 'Un brillo impecable,',
      titleScript: 'siempre',
      sub: 'Golden Shine lleva limpiadores verificados y asegurados a tu puerta. Reserva en dos minutos — nosotros llevamos los productos, el cuidado y el brillo.',
      ctaPrimary: 'Cotización gratis',
      ctaSecondary: 'Ver servicios',
      stat1: '4.9/5 de calificación',
      stat2: '+2,400 casas limpiadas',
      trust: 'Asegurados y verificados · Garantía de satisfacción 100%',
    },
    services: {
      eyebrow: 'Qué hacemos',
      title: 'Limpieza para cada espacio',
      sub: 'Desde un repaso rápido hasta una limpieza profunda — elige lo que necesites.',
      items: [
        { icon: 'Home2', name: 'Limpieza de Casas', desc: 'Mantenimiento regular de cocinas, baños, pisos y salas.', from: 'desde $89' },
        { icon: 'Building', name: 'Oficinas y Comercial', desc: 'Limpieza confiable para oficinas, clínicas y locales.', from: 'a medida' },
        { icon: 'Sparkles', name: 'Limpieza Profunda', desc: 'Una limpieza detallada de arriba a abajo para todo el hogar.', from: 'desde $189' },
        { icon: 'Truck', name: 'Mudanzas (Entrada/Salida)', desc: 'Déjalo impecable — o llega a un comienzo limpio y fresco.', from: 'desde $229' },
        { icon: 'Sofa', name: 'Alfombras y Tapicería', desc: 'Alfombras, tapetes y muebles limpiados al vapor.', from: 'desde $99' },
        { icon: 'Wand', name: 'Post-Construcción', desc: 'Polvo, escombros y detalle tras una remodelación.', from: 'a medida' },
      ],
      cta: 'Cotizar',
    },
    how: {
      eyebrow: 'Simple y flexible',
      title: 'Cómo funciona',
      steps: [
        { icon: 'Calendar', name: 'Reserva en línea', desc: 'Cuéntanos sobre tu espacio y elige la hora que te convenga.' },
        { icon: 'Spray', name: 'Limpiamos', desc: 'Nuestro equipo asegurado llega a tiempo con todo lo necesario.' },
        { icon: 'CheckCircle', name: 'Tú descansas', desc: 'Disfruta un espacio impecable — garantizado, o lo corregimos.' },
      ],
    },
    why: {
      title: 'Por qué Golden Shine',
      items: [
        { icon: 'Shield', name: 'Asegurados y verificados', desc: 'Cada limpiador está verificado y totalmente asegurado.' },
        { icon: 'Leaf', name: 'Eco-amigable', desc: 'Productos seguros y no tóxicos — buenos para niños y mascotas.' },
        { icon: 'Clock', name: 'Siempre a tiempo', desc: 'Respetamos tu horario y llegamos cuando lo decimos.' },
        { icon: 'CheckCircle', name: 'Garantía 100%', desc: '¿No te gustó? Lo limpiamos de nuevo gratis en 24 horas.' },
      ],
    },
    reviews: {
      eyebrow: 'Queridos por la comunidad',
      title: 'Lo que dicen nuestros clientes',
      rating: '4.9 de 5 · 312 reseñas',
      items: [
        { name: 'María L.', city: 'Houston, TX', text: 'Dejaron mi cocina absolutamente impecable. Reservar tomó dos minutos y el equipo fue muy amable.', stars: 5 },
        { name: 'James P.', city: 'Houston, TX', text: 'Usamos Golden Shine para nuestra oficina cada semana. Siempre puntuales, siempre minuciosos.', stars: 5 },
        { name: 'Aisha K.', city: 'Katy, TX', text: 'La limpieza profunda antes de mudarnos nos devolvió todo el depósito. Vale cada centavo.', stars: 5 },
      ],
    },
    quote: {
      eyebrow: 'Gratis, sin compromiso',
      title: 'Obtén tu cotización',
      sub: 'Cuéntanos sobre tu espacio y te enviaremos un precio por mensaje en menos de una hora.',
      name: 'Nombre completo', namePh: 'María López',
      phone: 'Teléfono', phonePh: '(555) 123-4567',
      email: 'Correo', emailPh: 'tu@correo.com',
      service: 'Tipo de servicio', servicePh: 'Elige un servicio',
      serviceOpts: ['Limpieza de Casas', 'Oficinas y Comercial', 'Limpieza Profunda', 'Mudanzas', 'Alfombras y Tapicería', 'Post-Construcción'],
      size: 'Tamaño del lugar', sizePh: 'Selecciona el tamaño',
      sizeOpts: ['Estudio / 1 recámara', '2 recámaras', '3 recámaras', '4+ recámaras', 'Oficina / comercial'],
      freq: '¿Con qué frecuencia?',
      freqOpts: ['Una vez', 'Semanal', 'Cada 2 semanas', 'Mensual'],
      addons: 'Extras',
      addonOpts: ['Por dentro del horno', 'Ventanas interiores', 'Por dentro del refri', 'Lavado y doblado'],
      submit: 'Solicitar cotización',
      consent: 'Acepto que me contacten sobre mi cotización.',
      successTitle: '¡Cotización solicitada!',
      successSub: 'Gracias — te enviaremos un precio por mensaje en menos de una hora. Mantente pendiente de tu teléfono.',
      again: 'Solicitar otra',
    },
    footer: {
      tagline: 'Limpieza de casas y oficinas en la que puedes confiar.',
      hours: 'Lun–Sáb · 8am–7pm',
      area: 'Atendiendo Houston y alrededores',
      col1: 'Servicios', col2: 'Compañía', col3: 'Contáctanos',
      company: ['Sobre nosotros', 'Empleo', 'Reseñas', 'Tarjetas de regalo'],
      rights: '© 2026 Golden Shine Cleaning Service. Todos los derechos reservados.',
    },
    langLabel: 'EN',
  },
};
